CREATE TABLE users
(
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    external_id UUID UNIQUE,
    username    VARCHAR(255) NOT NULL,
    CONSTRAINT users_username_unique UNIQUE (username),
    password    VARCHAR(1024),
    enabled     BOOLEAN      NOT NULL DEFAULT TRUE,
    locked      BOOLEAN      NOT NULL DEFAULT FALSE,
    created_by  BIGINT       REFERENCES users (id) ON DELETE SET NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by  BIGINT       REFERENCES users (id) ON DELETE SET NULL,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_by  BIGINT       REFERENCES users (id) ON DELETE SET NULL,
    deleted_at  TIMESTAMPTZ
);

CREATE INDEX idx_users_external_id ON users (external_id);

-- Comments
COMMENT ON TABLE users IS
    'Core system users (administrators, end-users, etc.). Handles authentication and global identifiers.';

COMMENT ON COLUMN users.username IS
    'Unique login identifier (3-64 chars). Allowed: alphanumeric, dot, dash, underscore. '
        'Must start/end with alphanumeric. No consecutive special chars.';

COMMENT ON COLUMN users.password IS
    'Securely hashed password (BCrypt or Argon2id). Never store plaintext. Length 1024 reserved for future algorithms.';

COMMENT ON COLUMN users.enabled IS
    'Flag to strictly disable access without deleting the record.';

COMMENT ON COLUMN users.deleted_at IS
    'Soft delete time stamp. If not NULL, the user is considered inactive/deleted.';

-- Index & Trigger
CREATE INDEX idx_users_username_active ON users (username) WHERE deleted_at IS NULL;

CREATE TRIGGER trg_users_set_updated
    BEFORE UPDATE
    ON users
    FOR EACH ROW
EXECUTE FUNCTION trigger_set_updated();


