-- Database: old

-- DROP DATABASE IF EXISTS old;

CREATE DATABASE datum
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    ICU_LOCALE = 'und'
    LOCALE_PROVIDER = 'icu'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

ALTER DATABASE datum    SET "TimeZone" TO 'UTC';


CREATE OR REPLACE FUNCTION trigger_set_updated()
    RETURNS TRIGGER AS
$$
BEGIN
    NEW.updated_at := now();
RETURN NEW;
END;
$$ LANGUAGE plpgsql;


CREATE TABLE users
(
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    external_id UUID UNIQUE,
    username    VARCHAR(255) NOT NULL,
    CONSTRAINT users_username_unique UNIQUE (username),
    password    VARCHAR(1024),
    enabled     BOOLEAN      NOT NULL DEFAULT TRUE,
    locked      BOOLEAN      NOT NULL DEFAULT FALSE,
    created_by  BIGINT       REFERENCES users (id) ON DELETE SET NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by  BIGINT       REFERENCES users (id) ON DELETE SET NULL,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_by  BIGINT       REFERENCES users (id) ON DELETE SET NULL,
    deleted_at  TIMESTAMPTZ
);

CREATE INDEX idx_users_external_id ON users (external_id);

CREATE INDEX idx_users_username_active ON users (username) WHERE deleted_at IS NULL;

CREATE TRIGGER trg_users_set_updated
    BEFORE UPDATE
    ON users
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_updated();

CREATE TABLE language
(
    language   CHAR(2) PRIMARY KEY,  -- ISO 639-1: 'ru', 'en'
    native     VARCHAR(50) NOT NULL, -- 'Русский', 'English'
    i18n JSONB NOT NULL DEFAULT '{}',

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

-- Trigger
CREATE TRIGGER trg_language_set_updated
    BEFORE UPDATE
    ON language
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_updated();

CREATE TABLE gender
(
    code       CHAR(1) PRIMARY KEY CHECK (code IN ('M', 'F', '<')),
    i18n JSONB NOT NULL DEFAULT '{}',
    short_i18n JSONB NOT NULL DEFAULT '{}', -- Для сокращений "М", "Ж", "F"
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX idx_gender_unique ON gender (code) WHERE deleted_at IS NULL;


CREATE TABLE phone
(
    id           BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    number       VARCHAR(20) NOT NULL,
    -- E.164 format validation (+ followed by 7-15 digits)
    CONSTRAINT phone_number_check CHECK (number ~ '^[a-zA-Z0-9.!#$%&*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)+$'),
    CONSTRAINT phone_number_unique UNIQUE (number),

    has_whatsapp BOOLEAN     NOT NULL DEFAULT FALSE,
    has_telegram BOOLEAN     NOT NULL DEFAULT FALSE,

    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at   TIMESTAMPTZ
);

CREATE TRIGGER trg_phone_set_updated
    BEFORE UPDATE
    ON phone
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_updated();

CREATE TABLE email
(
    id         BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    address    VARCHAR(255) NOT NULL,
    CONSTRAINT email_check CHECK (address ~ '^.+@.+\..+$'),
    CONSTRAINT email_unique UNIQUE (address),

    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

CREATE TRIGGER trg_email_set_updated
    BEFORE UPDATE
    ON email
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_updated();

CREATE TABLE contact_type
(
    type       VARCHAR(20) PRIMARY KEY, -- 'HOME', 'WORK', 'OTHER'
    i18n       JSONB       NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

CREATE TABLE user_phone
(
    user_id      BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    phone_id     BIGINT      NOT NULL REFERENCES phone (id) ON DELETE RESTRICT,
    contact_type VARCHAR(20) REFERENCES contact_type (type) ON DELETE SET NULL,

    is_primary   BOOLEAN     NOT NULL DEFAULT FALSE,
    is_verified  BOOLEAN     NOT NULL DEFAULT FALSE,

    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (user_id, phone_id)
);

CREATE UNIQUE INDEX idx_user_phone_primary ON user_phone (user_id) WHERE is_primary IS TRUE;

CREATE TABLE user_email
(
    user_id      BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    email_id     BIGINT      NOT NULL REFERENCES email (id) ON DELETE RESTRICT,
    contact_type VARCHAR(20) REFERENCES contact_type (type) ON DELETE SET NULL,

    is_primary   BOOLEAN     NOT NULL DEFAULT FALSE,
    is_verified  BOOLEAN     NOT NULL DEFAULT FALSE,

    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (user_id, email_id)
);

CREATE UNIQUE INDEX idx_user_email_primary ON user_email (user_id) WHERE is_primary IS TRUE;

CREATE TABLE country
(
    id         BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    iso_alpha2 CHAR(2)     NOT NULL,
    iso_alpha3 CHAR(3)     NOT NULL,
    is_active  BOOLEAN     NOT NULL DEFAULT TRUE,
    i18n       JSONB       NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX idx_country_iso2_unique ON country (iso_alpha2) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX idx_country_iso3_unique ON country (iso_alpha3) WHERE deleted_at IS NULL;

CREATE INDEX idx_country_i18n ON country USING GIN (i18n);

CREATE TRIGGER trg_country_updated
    BEFORE UPDATE
    ON country
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_updated();

CREATE TABLE phone_code
(
    id         BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    country_id BIGINT      NOT NULL REFERENCES country (id) ON DELETE CASCADE,

    prefix     VARCHAR(10) NOT NULL, -- '996', '7', '1'
    mask       VARCHAR(50),          -- '(###) ##-##-##' (для фронтенда)
    emoji      VARCHAR(5),           -- '🇰🇬', '🇷🇺'

    regex      VARCHAR(255),
    is_main    BOOLEAN     DEFAULT TRUE,

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

CREATE INDEX idx_country_phone_code_prefix ON phone_code (prefix);

CREATE TABLE region
(
    id         BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    country_id BIGINT      NOT NULL REFERENCES country (id) ON DELETE CASCADE,
    code       VARCHAR(20),
    i18n       JSONB       NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);
CREATE TRIGGER trg_region_updated
    BEFORE UPDATE
    ON region
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_updated();

CREATE TABLE city
(
    id         BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    country_id BIGINT      NOT NULL REFERENCES country (id) ON DELETE RESTRICT,
    region_id  BIGINT      REFERENCES region (id) ON DELETE SET NULL,
    latitude   DECIMAL(10, 8),
    longitude  DECIMAL(11, 8),
    is_active  BOOLEAN     NOT NULL DEFAULT TRUE,
    i18n       JSONB       NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);
CREATE TRIGGER trg_city_updated
    BEFORE UPDATE
    ON city
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_updated();

CREATE INDEX idx_city_country_region ON city (country_id, region_id);

CREATE TABLE street
(
    id            BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    city_id       BIGINT      NOT NULL REFERENCES city (id) ON DELETE CASCADE,
    external_code VARCHAR(100),
    i18n          JSONB       NOT NULL DEFAULT '{}',
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at    TIMESTAMPTZ
);

CREATE TRIGGER trg_street_updated
    BEFORE UPDATE
    ON street
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_updated();

CREATE TABLE address
(
    id          BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,

    city_id     BIGINT      NOT NULL REFERENCES city (id) ON DELETE RESTRICT,
    street_id   BIGINT      NOT NULL REFERENCES street (id) ON DELETE RESTRICT,
    building    VARCHAR(50), -- '125/1'
    apartment   VARCHAR(20), -- 'кв 5'
    floor       VARCHAR(10),
    entrance    VARCHAR(10),
    postal_code VARCHAR(20),
    latitude    DECIMAL(10, 8),
    longitude   DECIMAL(11, 8),
    comment     VARCHAR(255),
    -- Аудит
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by  BIGINT      REFERENCES users (id) ON DELETE SET NULL,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by  BIGINT      REFERENCES users (id) ON DELETE SET NULL,
    deleted_at  TIMESTAMPTZ,
    deleted_by  BIGINT      REFERENCES users (id) ON DELETE SET NULL
);

CREATE TRIGGER trg_address_updated
    BEFORE UPDATE
    ON address
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_updated();

CREATE TABLE role
(
    role             VARCHAR(50) PRIMARY KEY,
    i18n             JSONB       NOT NULL DEFAULT '{}',
    description_i18n JSONB       NOT NULL DEFAULT '{}',

    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at       TIMESTAMPTZ
);

CREATE TRIGGER trg_role_updated
    BEFORE UPDATE
    ON role
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_updated();

CREATE TABLE person
(
    id             BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    user_id        BIGINT UNIQUE REFERENCES users (id) ON DELETE SET NULL,

    last_name      VARCHAR(100)  NOT NULL,
    first_name     VARCHAR(100)  NOT NULL,
    middle_name    VARCHAR(100),

    birth_date     DATE          NOT NULL,
    gender         CHAR(1)       NOT NULL REFERENCES gender (code),
    citizenship_id BIGINT REFERENCES country (id),

    created_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    created_by     BIGINT        REFERENCES users (id) ON DELETE SET NULL,
    updated_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_by     BIGINT        REFERENCES users (id) ON DELETE SET NULL,
    deleted_at     TIMESTAMPTZ,
    deleted_by     BIGINT        REFERENCES users (id) ON DELETE SET NULL
);

CREATE TRIGGER trg_person_updated
    BEFORE UPDATE
    ON person
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_updated();

CREATE TABLE identity_document
(
    id                  BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    person_id           BIGINT      NOT NULL REFERENCES person (id) ON DELETE CASCADE,

    document_type       VARCHAR(2)  NOT NULL,
    doc_number          VARCHAR(50) NOT NULL,
    serial              VARCHAR(20),
    authority           VARCHAR(255),
    issue_date          DATE        NOT NULL,

    issuing_country_id  BIGINT      NOT NULL REFERENCES country (id),

    mrz_string_1        VARCHAR(44),
    mrz_string_2        VARCHAR(44),
    mrz_string_3        VARCHAR(30),

    mrz_surname         VARCHAR(100),
    mrz_given_names     VARCHAR(100),
    mrz_doc_number      VARCHAR(20),
    mrz_birth_date      DATE,
    mrz_expiry_date     DATE        NOT NULL,
    mrz_personal_number VARCHAR(20),

    mrz_sex_code        CHAR(1) REFERENCES gender (code),

    mrz_nationality_id  BIGINT REFERENCES country (id),

    is_primary          BOOLEAN     NOT NULL DEFAULT FALSE,
    is_active           BOOLEAN     NOT NULL DEFAULT TRUE,

    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by          BIGINT      REFERENCES users (id) ON DELETE SET NULL,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by          BIGINT      REFERENCES users (id) ON DELETE SET NULL,
    deleted_at          TIMESTAMPTZ,
    deleted_by          BIGINT      REFERENCES users (id) ON DELETE SET NULL,

    CONSTRAINT id_doc_unique UNIQUE (issuing_country_id, document_type, doc_number)
);

CREATE TRIGGER trg_identity_document_updated
    BEFORE UPDATE
    ON identity_document
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_updated();

CREATE UNIQUE INDEX idx_identity_doc_primary
    ON identity_document (person_id)
    WHERE is_primary IS TRUE AND deleted_at IS NULL;


CREATE TABLE storage_file
(
    id            BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    -- Имя файла, которое видел пользователь при загрузке ("passport_scan.jpg")
    original_name VARCHAR(255) NOT NULL,
    -- Тип содержимого (MIME-type), чтобы браузер знал, как открывать ("image/jpeg", "application/pdf")
    mime_type     VARCHAR(100) NOT NULL,
    -- Размер в байтах (полезно для статистики и UI)
    size          BIGINT       NOT NULL,
    -- S3 Bucket (или папка), где лежит файл ("avatars", "passports", "documents")
    bucket        VARCHAR(100) NOT NULL,
    -- Путь внутри бакета (Key). Например: "2025/12/06/uuid-uuid.jpg"
    -- Мы НЕ храним полный домен (https://s3.amazon...), потому что домены меняются.
    path          VARCHAR(512) NOT NULL,
    -- Публичный ли файл? (Если FALSE, то для скачивания нужна presigned link)
    is_public     BOOLEAN      NOT NULL DEFAULT FALSE,
    -- Аудит
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by    BIGINT       REFERENCES users (id) ON DELETE SET NULL,
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_by    BIGINT       REFERENCES users (id) ON DELETE SET NULL,
    deleted_at    TIMESTAMPTZ,
    deleted_by    BIGINT       REFERENCES users (id) ON DELETE SET NULL,
    -- Защита от дублей по пути (в одном бакете)
    CONSTRAINT uq_storage_file_path UNIQUE (bucket, path)
);

-- Триггер обновления времени
CREATE TRIGGER trg_storage_file_updated
    BEFORE UPDATE
    ON storage_file
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_updated();


CREATE TABLE photo_type
(
    code        VARCHAR(50) PRIMARY KEY, -- 'AVATAR', 'FULL_BODY', 'FACE_ISO'
    description VARCHAR(255),            -- Техническое описание (напр. "For biometric matching")
    i18n        JSONB       NOT NULL DEFAULT '{}',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at  TIMESTAMPTZ
);

CREATE TABLE person_photo
(
    id              BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    person_id       BIGINT      NOT NULL REFERENCES person (id) ON DELETE CASCADE,
    storage_file_id BIGINT      NOT NULL REFERENCES storage_file (id) ON DELETE RESTRICT,
    type            VARCHAR(50) NOT NULL REFERENCES photo_type (code) ON DELETE RESTRICT,
    is_primary      BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by      BIGINT      REFERENCES users (id) ON DELETE SET NULL,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by      BIGINT      REFERENCES users (id) ON DELETE SET NULL,
    deleted_at      TIMESTAMPTZ,
    deleted_by      BIGINT      REFERENCES users (id) ON DELETE SET NULL
);

-- Триггер обновления времени
CREATE TRIGGER trg_person_photo_updated
    BEFORE UPDATE
    ON person_photo
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_updated();

CREATE UNIQUE INDEX idx_person_photo_primary_per_type
    ON person_photo (person_id, type)
    WHERE is_primary IS TRUE AND deleted_at IS NULL;

CREATE TABLE relation_type
(
    code       VARCHAR(50) PRIMARY KEY, -- 'FATHER', 'MOTHER', 'GUARDIAN'
    CONSTRAINT check_relation_type_code CHECK (code ~ '^[A-Z_]+$' AND length(code) BETWEEN 3 AND 50),
    i18n       JSONB       NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

-- 2. Таблица связей
CREATE TABLE person_relation
(
    id            BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    person_id     BIGINT      NOT NULL REFERENCES person (id) ON DELETE CASCADE,
    relative_id   BIGINT      NOT NULL REFERENCES person (id) ON DELETE CASCADE,
    relation_type VARCHAR(50) NOT NULL REFERENCES relation_type (code),
    is_biological BOOLEAN              DEFAULT TRUE,

    created_by    BIGINT      REFERENCES users (id) ON DELETE SET NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by    BIGINT      REFERENCES users (id) ON DELETE SET NULL,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_by    BIGINT      REFERENCES users (id) ON DELETE SET NULL,
    deleted_at    TIMESTAMPTZ,

    CONSTRAINT check_relation_self CHECK (person_id <> relative_id),
    UNIQUE (person_id, relative_id, relation_type)
);

CREATE TABLE currency
(
    code       CHAR(3) PRIMARY KEY, -- ISO 4217: 'USD', 'EUR', 'KGS', 'RUB'
    symbol     VARCHAR(5) NOT NULL, -- '$', '€', 'с', '₽'
    decimals   SMALLINT   NOT NULL DEFAULT 2, -- 2 для USD/KGS, 0 для JPY
    i18n JSONB NOT NULL DEFAULT '{}',

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

-- Триггер
CREATE TRIGGER trg_currency_updated BEFORE UPDATE ON currency FOR EACH ROW EXECUTE FUNCTION trigger_set_updated();





