-- Database configuration
ALTER DATABASE datum SET "TimeZone" TO 'UTC';

/* ==========================================================================
   1. STATIC DICTIONARIES
   ========================================================================== */

CREATE TABLE role
(
    role             VARCHAR(50) PRIMARY KEY,
    i18n             JSONB NOT NULL DEFAULT '{}',
    description_i18n JSONB NOT NULL DEFAULT '{}',
    updated_at       TIMESTAMPTZ
);

CREATE TABLE language
(
    language   CHAR(2) PRIMARY KEY,
    native     VARCHAR(50) NOT NULL,
    i18n       JSONB       NOT NULL DEFAULT '{}',
    updated_at TIMESTAMPTZ
);

CREATE TABLE gender
(
    code       CHAR(1) PRIMARY KEY CHECK (code IN ('M', 'F', 'X')),
    i18n       JSONB NOT NULL DEFAULT '{}',
    short_i18n JSONB NOT NULL DEFAULT '{}',
    updated_at TIMESTAMPTZ
);

CREATE TABLE contact_type
(
    type       VARCHAR(20) PRIMARY KEY,
    i18n       JSONB NOT NULL DEFAULT '{}',
    updated_at TIMESTAMPTZ
);

CREATE TABLE relation_type
(
    code       VARCHAR(50) PRIMARY KEY,
    CONSTRAINT check_relation_type_code CHECK (code ~ '^[A-Z_]+$' AND length(code) BETWEEN 3 AND 50),
    i18n       JSONB NOT NULL DEFAULT '{}',
    updated_at TIMESTAMPTZ
);

CREATE TABLE photo_type
(
    code        VARCHAR(50) PRIMARY KEY,
    description VARCHAR(255),
    i18n        JSONB NOT NULL DEFAULT '{}',
    updated_at  TIMESTAMPTZ
);

/* ==========================================================================
   2. USERS
   ========================================================================== */

CREATE TABLE users
(
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    external_id UUID UNIQUE,
    username    VARCHAR(255) NOT NULL,
    password    VARCHAR(1024),
    enabled     BOOLEAN      NOT NULL DEFAULT TRUE,
    locked      BOOLEAN      NOT NULL DEFAULT FALSE,

    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL,
    deleted_at  TIMESTAMPTZ,

    CONSTRAINT users_username_unique UNIQUE NULLS NOT DISTINCT (username, deleted_at)
);
CREATE INDEX idx_users_external_id ON users (external_id);

CREATE TABLE user_role
(
    user_id BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role    VARCHAR(50) NOT NULL REFERENCES role (role) ON DELETE RESTRICT,
    PRIMARY KEY (user_id, role)
);

/* ==========================================================================
   3. GEOGRAPHIC
   ========================================================================== */

CREATE TABLE country
(
    id         BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    iso_alpha2 CHAR(2) NOT NULL,
    iso_alpha3 CHAR(3) NOT NULL,
    is_active  BOOLEAN NOT NULL DEFAULT TRUE,
    i18n       JSONB   NOT NULL DEFAULT '{}',
    updated_at TIMESTAMPTZ,

    CONSTRAINT uq_country_iso2 UNIQUE (iso_alpha2),
    CONSTRAINT uq_country_iso3 UNIQUE (iso_alpha3)
);

CREATE TABLE currency
(
    code       CHAR(3) PRIMARY KEY, -- 'USD', 'EUR'
    symbol     VARCHAR(5) NOT NULL, -- '$', '€'
    decimals   SMALLINT   NOT NULL DEFAULT 2,
    i18n       JSONB      NOT NULL DEFAULT '{}',
    updated_at TIMESTAMPTZ
);

CREATE TABLE country_currency
(
    country_id    BIGINT REFERENCES country (id),
    currency_code CHAR(3) REFERENCES currency (code),
    PRIMARY KEY (country_id, currency_code)
);

CREATE TABLE phone_code
(
    id         BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    country_id BIGINT      NOT NULL REFERENCES country (id) ON DELETE CASCADE,
    prefix     VARCHAR(10) NOT NULL,
    CONSTRAINT check_phone_code_prefix CHECK (prefix ~ '^\+[0-9]+$'),
    mask       VARCHAR(50),
    emoji      VARCHAR(5),
    regex      VARCHAR(255),
    is_main    BOOLEAN DEFAULT TRUE,
    updated_at TIMESTAMPTZ
);

CREATE TABLE region
(
    id         BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    country_id BIGINT NOT NULL REFERENCES country (id) ON DELETE RESTRICT,
    code       VARCHAR(20),
    i18n       JSONB  NOT NULL DEFAULT '{}',
    updated_at TIMESTAMPTZ
);

CREATE TABLE city
(
    id         BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    country_id BIGINT  NOT NULL REFERENCES country (id) ON DELETE RESTRICT,
    region_id  BIGINT  REFERENCES region (id) ON DELETE SET NULL,
    latitude   DECIMAL(10, 8),
    longitude  DECIMAL(11, 8),
    is_active  BOOLEAN NOT NULL DEFAULT TRUE,
    i18n       JSONB   NOT NULL DEFAULT '{}',
    updated_at TIMESTAMPTZ
);
CREATE INDEX idx_city_country_region ON city (country_id, region_id);

/* ==========================================================================
   4. ADDRESS
   ========================================================================== */

CREATE TABLE address
(
    id          BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    city_id     BIGINT      NOT NULL REFERENCES city (id) ON DELETE RESTRICT,
    street_name VARCHAR(150),
    building    VARCHAR(50),
    apartment   VARCHAR(20),
    floor       VARCHAR(10),
    entrance    VARCHAR(10),
    postal_code VARCHAR(20),
    latitude    DECIMAL(10, 8),
    longitude   DECIMAL(11, 8),
    comment     VARCHAR(255),

    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL,
    deleted_at  TIMESTAMPTZ
);

/* ==========================================================================
   5. PERSON
   ========================================================================== */

CREATE TABLE person
(
    id             BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    last_name      VARCHAR(100) NOT NULL,
    first_name     VARCHAR(100) NOT NULL,
    middle_name    VARCHAR(100),
    birth_date     DATE,
    gender         CHAR(1)      NOT NULL REFERENCES gender (code),
    citizenship_id BIGINT       REFERENCES country (id) ON DELETE SET NULL,

    created_at     TIMESTAMPTZ  NOT NULL,
    updated_at     TIMESTAMPTZ  NOT NULL,
    deleted_at     TIMESTAMPTZ
);
CREATE INDEX idx_person_names ON person (last_name, first_name);
CREATE INDEX idx_person_birth ON person (birth_date);

CREATE TABLE identity_document
(
    id                  BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    person_id           BIGINT      NOT NULL REFERENCES person (id) ON DELETE CASCADE,
    type                VARCHAR(3)  NOT NULL,
    doc_number          VARCHAR(50) NOT NULL,
    serial              VARCHAR(20),
    authority           VARCHAR(255),
    issue_date          DATE        NOT NULL,
    expiry_date         DATE,
    issuing_country_id  BIGINT      NOT NULL REFERENCES country (id) ON DELETE RESTRICT,

    mrz_surname         VARCHAR(100),
    mrz_given_names     VARCHAR(100),
    mrz_doc_number      VARCHAR(20),
    mrz_birth_date      DATE,
    mrz_expiry_date     DATE,
    mrz_personal_number VARCHAR(20),
    mrz_sex_code        CHAR(1) REFERENCES gender (code),
    mrz_nationality_id  BIGINT REFERENCES country (id),

    is_primary          BOOLEAN     NOT NULL DEFAULT FALSE,
    is_active           BOOLEAN     NOT NULL DEFAULT TRUE,

    created_at          TIMESTAMPTZ NOT NULL,
    updated_at          TIMESTAMPTZ NOT NULL,
    deleted_at          TIMESTAMPTZ,

    CONSTRAINT uq_id_doc UNIQUE NULLS NOT DISTINCT (issuing_country_id, type, doc_number, deleted_at)
);
CREATE INDEX idx_identity_doc_number ON identity_document (doc_number) WHERE deleted_at IS NULL;
CREATE INDEX idx_identity_mrz_doc_number ON identity_document (mrz_doc_number) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX idx_identity_doc_primary ON identity_document (person_id) WHERE is_primary IS TRUE AND deleted_at IS NULL;

/* ==========================================================================
   6. FILES & PHOTOS
   ========================================================================== */

CREATE TABLE storage_file
(
    id            BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    original_name VARCHAR(1024) NOT NULL,
    mime_type     VARCHAR(100)  NOT NULL,
    size          BIGINT        NOT NULL,
    bucket        VARCHAR(100)  NOT NULL,
    path          VARCHAR(512)  NOT NULL,
    is_public     BOOLEAN       NOT NULL DEFAULT FALSE,

    created_at    TIMESTAMPTZ   NOT NULL,
    updated_at    TIMESTAMPTZ   NOT NULL,
    deleted_at    TIMESTAMPTZ,

    CONSTRAINT uq_storage_file_path UNIQUE NULLS NOT DISTINCT (bucket, path, deleted_at)
);

CREATE TABLE person_photo
(
    id              BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    person_id       BIGINT      NOT NULL REFERENCES person (id) ON DELETE CASCADE,
    storage_file_id BIGINT      NOT NULL REFERENCES storage_file (id) ON DELETE RESTRICT,
    type            VARCHAR(50) NOT NULL REFERENCES photo_type (code) ON DELETE RESTRICT,
    is_primary      BOOLEAN     NOT NULL DEFAULT FALSE,

    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL,
    deleted_at      TIMESTAMPTZ
);
CREATE UNIQUE INDEX idx_person_photo_primary_type ON person_photo (person_id, type) WHERE is_primary IS TRUE AND deleted_at IS NULL;

/* ==========================================================================
   7. RELATIONS
   ========================================================================== */

CREATE TABLE person_relation
(
    id            BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    person_id     BIGINT      NOT NULL REFERENCES person (id) ON DELETE CASCADE,
    relative_id   BIGINT      NOT NULL REFERENCES person (id) ON DELETE CASCADE,
    type          VARCHAR(50) NOT NULL REFERENCES relation_type (code),
    is_biological BOOLEAN DEFAULT TRUE,

    updated_at    TIMESTAMPTZ NOT NULL,

    CONSTRAINT check_relation_self CHECK (person_id <> relative_id),
    UNIQUE (person_id, relative_id, type)
);

/* ==========================================================================
   8. CONTACTS
   ========================================================================== */

CREATE TABLE phone
(
    id            BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    phone_code_id BIGINT      NOT NULL REFERENCES phone_code (id) ON DELETE RESTRICT,
    number        VARCHAR(20) NOT NULL,
    CONSTRAINT phone_number_check CHECK (number ~ '^[0-9]{4,15}$'),
    CONSTRAINT uq_phone_full UNIQUE (phone_code_id, number),
    has_whatsapp  BOOLEAN     NOT NULL DEFAULT FALSE,
    has_telegram  BOOLEAN     NOT NULL DEFAULT FALSE,
    updated_at    TIMESTAMPTZ NOT NULL
);

CREATE TABLE email_domain
(
    id         BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name       VARCHAR(255) NOT NULL UNIQUE,
    updated_at TIMESTAMPTZ  NOT NULL
);

CREATE INDEX idx_email_domain ON email (domain_id);

CREATE TABLE email
(
    id         BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    domain_id  BIGINT      NOT NULL REFERENCES email_domain (id) ON DELETE RESTRICT,
    local_part VARCHAR(64) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_email_address UNIQUE (local_part, domain_id)
);


-- Many-to-Many Links
CREATE TABLE person_phone
(
    person_id   BIGINT      NOT NULL REFERENCES person (id) ON DELETE CASCADE,
    phone_id    BIGINT      NOT NULL REFERENCES phone (id) ON DELETE CASCADE,
    type        VARCHAR(20) REFERENCES contact_type (type) ON DELETE SET NULL,
    is_primary  BOOLEAN     NOT NULL DEFAULT FALSE,
    is_verified BOOLEAN     NOT NULL DEFAULT FALSE,
    updated_at  TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (person_id, phone_id)
);
CREATE UNIQUE INDEX idx_person_phone_primary ON person_phone (person_id) WHERE is_primary IS TRUE;

CREATE TABLE person_email
(
    person_id   BIGINT      NOT NULL REFERENCES person (id) ON DELETE CASCADE,
    email_id    BIGINT      NOT NULL REFERENCES email (id) ON DELETE CASCADE,
    type        VARCHAR(20) REFERENCES contact_type (type) ON DELETE SET NULL,
    is_primary  BOOLEAN     NOT NULL DEFAULT FALSE,
    is_verified BOOLEAN     NOT NULL DEFAULT FALSE,
    updated_at  TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (person_id, email_id)
);
CREATE UNIQUE INDEX idx_person_email_primary ON person_email (person_id) WHERE is_primary IS TRUE;

CREATE TABLE user_phone
(
    user_id     BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    phone_id    BIGINT      NOT NULL REFERENCES phone (id) ON DELETE CASCADE,
    type        VARCHAR(20) REFERENCES contact_type (type) ON DELETE SET NULL,
    is_primary  BOOLEAN     NOT NULL DEFAULT FALSE,
    is_verified BOOLEAN     NOT NULL DEFAULT FALSE,
    updated_at  TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (user_id, phone_id)
);
CREATE UNIQUE INDEX idx_user_phone_primary ON user_phone (user_id) WHERE is_primary IS TRUE;

CREATE TABLE user_email
(
    user_id     BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    email_id    BIGINT      NOT NULL REFERENCES email (id) ON DELETE CASCADE,
    type        VARCHAR(20) REFERENCES contact_type (type) ON DELETE SET NULL,
    is_primary  BOOLEAN     NOT NULL DEFAULT FALSE,
    is_verified BOOLEAN     NOT NULL DEFAULT FALSE,
    updated_at  TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (user_id, email_id)
);
CREATE UNIQUE INDEX idx_user_email_primary ON user_email (user_id) WHERE is_primary IS TRUE;

/* ==========================================================================
   9. FINALIZING
   ========================================================================== */

ALTER TABLE users
    ADD COLUMN person_id BIGINT UNIQUE REFERENCES person (id) ON DELETE SET NULL;